madlib = ""
a = input("Verb ending in 'ing': ")
madlib += f"Espionage is the formal word for {a}. "
b = input("Adjective: ")
madlib += f"In the shadowy world of spies, a/an {b} organization like the US government "
c = input("Adjective: ")
madlib += f"uses spies to infiltrate {c} groups "
d = input("Plural Noun: ")
madlib += f"for the purpose of obtaining top secret {d}. "
e = input("Adjective: ")
madlib += f"For example, spies might have to crack the code for acessing confidential, {e} files, "
f = input("Person in Room: ")
madlib += f"or their mission could be far more dangerous - like stealing the key ingredient for making {f}'s "
g = input("Plural Noun: ")
madlib += f"award-winning Explosive Fudgy {g}. "
h = input("A Place: ")
madlib += f"Spies are found all over (the) {h} "
i = input("Adjective: ")
madlib += f"but they are not allowed to reveal their {i} identities. "
j = input("Celebrity: ")
madlib += f"A teacher, {j}, "
k = input("Noun: ")
madlib += f"or even the little old {k} with the cane "
l = input("Plural Noun: ")
madlib += f"and fifteen pet {l} who lives next door to you could be a spy. "
m = input("Adjective: ")
madlib += f"The world of spying might seem glamorous and {m} "
n = input("Plural Noun: ")
madlib += f"but it is filled with risks and {n}! "
o = input("Plural Noun: ")
madlib += f"Sure, spies have a never-ending supply of supercool electronic {o}, "
p = input("Noun: ")
madlib += f"but they can't trust any {p} "
q = input("Plural Noun: ")
madlib += f"which is why the number one rule of spies is to keep friends close... and {q} closer!"
print (madlib)
